### ISSUE TITLE
Bug: missing axios as dependency

### ISSUE THREAD

**Issue by wridgeu** [ui5-community/generator-ui5-add#6]
Hi @uxkjaer, 👋

I added the generator locally to fool around a bit and discovered that axios is missing as dependency in the project. 

![image](https://user-images.githubusercontent.com/14982812/177629852-a7a0dbab-a85b-49c6-aaf4-9907fc4de656.png)

**Comment by uxkjaer** [comment]
Thanks for that. I've added it as a dependency and published a new version
